### ISSUE TITLE
OP_RETURN outputs with zero value are rejected

### ISSUE THREAD

**Issue by blackstat** [CoinBlack/blackcoin#2]
OP_RETURN outputs with zero value are nonstandard and are not accepted to enter the mempool. 

‘ERROR: AcceptToMemoryPool : nonstandard transaction: dust’.

Fees are paid by other outputs.

**Comment by dzimbeck** [comment]
Isn't this by design? Enforcing a minimum of 5500 satoshis as a dust payment prevents the spamming of transactions to the network. In Halo I usually pay 5500 for a burn. Also, if you could spam low value inputs to an account that can raise the TX fee when it comes time to sign all of those inputs individually.

**Comment by KrzysiekJ** [comment]
Flood prevention should be done using fee policy (vide the idea of [dynamic minimum transaction fees](https://bitcointalk.org/index.php?topic=1376051.msg14195163)). Enforcing minimum transaction value would reasonably work only for `OP_RETURN` transactions.
